data:
  input_size: 32
initialize:
  seed: 1
training:
  batch_size: 128
  workers: 8
test:
  batch_size: 1000
  workers: 8
optimizer:
  name: 'sgd'
  lr: 0.1
  lr_decay_gamma: 0.1
  weight_decay: 1e-4
  momentum: 0.9
  lr_decay_schedule: (120, 140)
  max_epoch: 160
log:
  print_interval: 20
  checkpoint_interval: 20
